=encoding utf8

=head1 OpenData::Flow - um framework para fluxo de dados

=head2 OpenData

Tudo começou com um e-mail na L<lista da SP-PM|http://sao-paulo.pm.org/lista>,
no qual se falou de "hackear" dados públicos. 
Isso virou uma idéia de produzir um framework para buscar e 
analisar dados públicos. 
Logo, o L<Thiago Rondon|http://www.maluco.com.br/blog/> montou um 
L<repositório no GitHub|https://github.com/maluco/OpenData-BR> e começou a 
rabiscar umas idéias de código.

O L<OpenData-BR|http://www.opendatabr.org/> ainda tem um status de 
I<work in progress>, mas as expectativas e as perspectivas são muito 
animadoras.
 
=head2 Primeiras Idéias

=head3 buscar dados na web -> 'scrape'

=head3 primeiras implementações com codigo

    -> pouco modularizado

=head3 ETL - extract transform load

    -> classes  extractor, transformer, loader
    -> quanto mais desenvolviamos, mais parecia com um fluxo de dados

em dd/mm, começou a implantacao do data flow

=head2 Referências

=over 4

=back

=head2 Agradecimentos

=head2 Autor

Alexei "Russo" Znamensky E<lt> russoz no cpan org E<gt>

Blog: L<http://russoz.wordpress.com/>

LinkedIn:
L<http://www.linkedin.com/profile?viewProfile=&key=754668&trk=tab_pro>

=head2 Licença

Este texto está licenciado sob os termos da Creative Commons by-sa,
L<http://creativecommons.org/licenses/by-sa/3.0/br/>

=begin pod:xhtml

<center>
<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/br/"><img alt="Licença Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/br/">Creative Commons Attribution-ShareAlike License</a>.
</center>

=end pod:xhtml

=cut

